export const governanceRoles = [
  'CEO',
  'Group Functional HOD',
  'Group DISHA HSC PIC',
  'Auditor',
  'PIC',
  'Viewer',
  'System Administrator',
]

export const governanceDefaults = {
  organization: {
    locations: [],
    departments: [],
  },
  roles: [
    { roleName: 'CEO', mappedTo: 'CEO', description: 'Full organizational visibility, strategic oversight, final approver for critical findings and high-value actions, Cost approval', active: 'Yes' },
    { roleName: 'Group Functional HOD', mappedTo: 'Group Functional HOD', description: 'Full visibility across locations and functions, reviews performance and compliance. Functional head across all locations, responsible for governance, escalations and department performance', active: 'Yes' },
    { roleName: 'Group DISHA HSC PIC', mappedTo: 'Group DISHA HSC PIC', description: 'Group administrator for DISHA HSC, responsible for audit governance, approvals, checklist management and monitoring. Conducts audits, records observations, identifies gaps, verifies evidence and monitors improvement progress', active: 'Yes' },
    { roleName: 'Auditor', mappedTo: 'Branch DISHA PIC', description: 'Location-level DISHA coordinator responsible for audit planning, execution and follow-up', active: 'Yes' },
    { roleName: 'PIC', mappedTo: 'Location Functional HOD', description: 'Head of a department within a specific location, responsible for department compliance and action closure. Improvement Action owner responsible for root cause analysis, countermeasures and implementation', active: 'Yes' },
    { roleName: 'Viewer', mappedTo: 'Viewer', description: 'Read-only access to dashboards, reports and audit results', active: 'Yes' },
    { roleName: 'System Administrator', mappedTo: 'System Administrator', description: 'Full Access of website', active: 'Yes' },
  ],
  permissions: [
    { role: 'CEO', view: true, add: true, edit: true, delete: false, approve: true, verify: true, close: true, export: true, aiAccess: true },
    { role: 'Group Functional HOD', view: true, add: false, edit: false, delete: false, approve: true, verify: false, close: false, export: true, aiAccess: true },
    { role: 'Group DISHA HSC PIC', view: true, add: true, edit: true, delete: true, approve: true, verify: true, close: true, export: true, aiAccess: true },
    { role: 'Branch DISHA PIC', view: true, add: true, edit: true, delete: false, approve: true, verify: true, close: true, export: true, aiAccess: true },
    { role: 'Location Functional HOD', view: true, add: true, edit: true, delete: false, approve: false, verify: true, close: true, export: true, aiAccess: true },
    { role: 'Viewer', view: true, add: true, edit: true, delete: false, approve: false, verify: false, close: false, export: false, aiAccess: true },
    { role: 'System Administrator', view: true, add: true, edit: true, delete: true, approve: true, verify: true, close: true, export: true, aiAccess: true },
  ],
  approvalMatrix: [
    { approvalType: 'Cost Approval', approver: 'CEO' },
    { approvalType: 'Yokoten Approval', approver: 'CEO' },
    { approvalType: 'Closure Approval', approver: 'CEO' },
  ],
  escalationMatrix: [
    { eventType: 'Critical Finding', days: '0', escalateTo: 'Group Functional HOD' },
    { eventType: 'Critical Finding', days: '0', escalateTo: 'DISHA HSC PIC' },
    { eventType: 'Critical Finding', days: '0', escalateTo: 'CEO' },
    { eventType: 'Overdue Improvement Action', days: '1', escalateTo: 'Functional HOD' },
    { eventType: 'Overdue Improvement Action', days: '7', escalateTo: 'Group Functional HOD' },
    { eventType: 'Overdue Improvement Action', days: '15', escalateTo: 'CEO' },
    { eventType: 'Verification Pending', days: '7', escalateTo: 'Functional HOD' },
    { eventType: 'Verification Pending', days: '15', escalateTo: 'Group Functional HOD' },
    { eventType: 'Verification Pending', days: '30', escalateTo: 'CEO' },
    { eventType: 'Audit Not Started', days: '0', escalateTo: 'Branch DISHA PIC' },
    { eventType: 'Audit Not Started', days: '3', escalateTo: 'DISHA HSC PIC' },
    { eventType: 'Audit Not Started', days: '7', escalateTo: 'CEO' },
    { eventType: 'Audit Overdue', days: '0', escalateTo: 'Branch DISHA PIC' },
    { eventType: 'Audit Overdue', days: '5', escalateTo: 'DISHA HSC PIC' },
    { eventType: 'Audit Overdue', days: '10', escalateTo: 'CEO' },
    { eventType: 'Repeat Finding (3 Consecutive Audits)', days: '0', escalateTo: 'Group Functional HOD' },
    { eventType: 'Repeat Finding (3 Consecutive Audits)', days: '0', escalateTo: 'DISHA HSC PIC' },
    { eventType: 'Repeat Finding (3 Consecutive Audits)', days: '0', escalateTo: 'CEO' },
  ],
  aiGovernance: [
    { feature: 'Root Cause Suggestion', enabled: 'Yes', approver: 'Branch DISHA PIC' },
    { feature: '5 Why Suggestion', enabled: 'Yes', approver: 'Branch DISHA PIC' },
    { feature: 'Countermeasure Suggestion', enabled: 'Yes', approver: 'Branch DISHA PIC' },
    { feature: 'Yokoten Suggestion', enabled: 'Yes', approver: 'Group Functional HOD' },
    { feature: 'Executive Summary Generation', enabled: 'Yes', approver: 'DISHA HSC PIC, Location Functional HOD' },
    { feature: 'Audit Observation Summary', enabled: 'Yes', approver: 'Branch DISHA PIC' },
    { feature: 'Improvement Action Drafting', enabled: 'Yes', approver: 'Branch DISHA PIC' },
    { feature: 'Verification Comments Suggestion', enabled: 'Yes', approver: 'Branch DISHA PIC' },
    { feature: 'Risk Classification Suggestion', enabled: 'Yes', approver: 'Branch DISHA PIC' },
    { feature: 'Repeat Finding Analysis', enabled: 'Yes', approver: 'Group Functional HOD' },
    { feature: 'Department Improvement Insights', enabled: 'Yes', approver: 'Group Functional HOD' },
    { feature: 'Management Review Summary', enabled: 'Yes', approver: 'CEO' },
    { feature: 'Escalation Recommendation', enabled: 'Yes', approver: 'Group DISHA HSC PIC' },
    { feature: 'Compliance Trend Analysis', enabled: 'Yes', approver: 'Group DISHA HSC PIC' },
    { feature: 'Corrective Action Recommendation', enabled: 'Yes', approver: 'Branch DISHA PIC' },
    { feature: 'AI Risk Assessment', enabled: 'Yes', approver: 'DISHA HSC PIC' },
    { feature: 'AI Executive Review Draft', enabled: 'Yes', approver: 'CEO' },
  ],
  evidenceGovernance: [
    { evidenceType: 'Audit Photo', uploadAllowed: 'Yes', editAllowed: 'Yes (Before Audit Closure)', deleteAllowed: 'No', retentionPeriod: '5 Years', ownerRole: 'Auditor / Branch DISHA PIC', mandatory: 'Yes' },
    { evidenceType: 'Audit Document', uploadAllowed: 'Yes', editAllowed: 'Yes (Before Audit Closure)', deleteAllowed: 'No', retentionPeriod: '5 Years', ownerRole: 'Auditor / Branch DISHA PIC', mandatory: 'Conditional' },
    { evidenceType: 'Improvement Action Photo', uploadAllowed: 'Yes', editAllowed: 'Yes (Before Verification)', deleteAllowed: 'No', retentionPeriod: '5 Years', ownerRole: 'PIC / Location Functional HOD', mandatory: 'Yes' },
    { evidenceType: 'Improvement Action Document', uploadAllowed: 'Yes', editAllowed: 'Yes (Before Verification)', deleteAllowed: 'No', retentionPeriod: '5 Years', ownerRole: 'PIC / Location Functional HOD', mandatory: 'Conditional' },
    { evidenceType: 'Verification Evidence', uploadAllowed: 'Yes', editAllowed: 'No', deleteAllowed: 'No', retentionPeriod: '5 Years', ownerRole: 'Group DISHA HSC PIC / Branch DISHA PIC', mandatory: 'Yes' },
    { evidenceType: 'Yokoten Attachment', uploadAllowed: 'Yes', editAllowed: 'Yes', deleteAllowed: 'No', retentionPeriod: 'Permanent', ownerRole: 'Group Functional HOD / Group DISHA HSC PIC', mandatory: 'No' },
    { evidenceType: 'SOP / Reference Material', uploadAllowed: 'Yes', editAllowed: 'Yes', deleteAllowed: 'Archive Only', retentionPeriod: 'Permanent', ownerRole: 'Group DISHA HSC PIC / System Administrator', mandatory: 'No' },
    { evidenceType: 'Checklist Attachment', uploadAllowed: 'Yes', editAllowed: 'Yes', deleteAllowed: 'No', retentionPeriod: 'Permanent', ownerRole: 'Group DISHA HSC PIC / Branch DISHA PIC', mandatory: 'No' },
    { evidenceType: 'AI Generated Summary', uploadAllowed: 'Auto', editAllowed: 'No', deleteAllowed: 'No', retentionPeriod: '3 Years', ownerRole: 'Group DISHA HSC PIC', mandatory: 'No' },
    { evidenceType: 'Audit Report PDF', uploadAllowed: 'Auto', editAllowed: 'No', deleteAllowed: 'No', retentionPeriod: '5 Years', ownerRole: 'Group DISHA HSC PIC', mandatory: 'No' },
  ],
  notificationRules: [
    { event: 'Audit Assigned', recipientRole: 'Auditor', priority: 'High', enabled: 'Yes' },
    { event: 'Audit Due Tomorrow', recipientRole: 'Auditor', priority: 'High', enabled: 'Yes' },
    { event: 'Audit Overdue', recipientRole: 'Auditor', priority: 'Critical', enabled: 'Yes' },
    { event: 'Audit Submitted', recipientRole: 'DISHA HSC PIC', priority: 'Medium', enabled: 'Yes' },
    { event: 'Audit Approved', recipientRole: 'Branch DISHA PIC', priority: 'Medium', enabled: 'Yes' },
    { event: 'Critical Finding Raised', recipientRole: 'Group Functional HOD', priority: 'Critical', enabled: 'Yes' },
    { event: 'Critical Finding Raised', recipientRole: 'DISHA HSC PIC', priority: 'Critical', enabled: 'Yes' },
    { event: 'Critical Finding Raised', recipientRole: 'CEO', priority: 'Critical', enabled: 'Yes' },
    { event: 'Improvement Action Assigned', recipientRole: 'PIC', priority: 'High', enabled: 'Yes' },
    { event: 'Root Cause Pending', recipientRole: 'PIC', priority: 'High', enabled: 'Yes' },
    { event: 'Countermeasure Pending', recipientRole: 'PIC', priority: 'High', enabled: 'Yes' },
    { event: 'Cost Approval Required (< INR 5,000)', recipientRole: 'DISHA HSC PIC', priority: 'High', enabled: 'Yes' },
    { event: 'Cost Approval Required (> INR 5,000)', recipientRole: 'CEO', priority: 'Critical', enabled: 'Yes' },
    { event: 'Improvement Action Overdue', recipientRole: 'Functional HOD', priority: 'High', enabled: 'Yes' },
    { event: 'Improvement Action Overdue (7 Days)', recipientRole: 'Group Functional HOD', priority: 'Critical', enabled: 'Yes' },
    { event: 'Improvement Action Overdue (15 Days)', recipientRole: 'CEO', priority: 'Critical', enabled: 'Yes' },
    { event: 'Evidence Uploaded', recipientRole: 'Auditor', priority: 'Medium', enabled: 'Yes' },
    { event: 'Verification Pending', recipientRole: 'Auditor', priority: 'High', enabled: 'Yes' },
    { event: 'Verification Failed', recipientRole: 'PIC', priority: 'Critical', enabled: 'Yes' },
    { event: 'Improvement Reopened', recipientRole: 'PIC', priority: 'Critical', enabled: 'Yes' },
    { event: 'Yokoten Submitted', recipientRole: 'Group Functional HOD', priority: 'Medium', enabled: 'Yes' },
    { event: 'Yokoten Approved', recipientRole: 'DISHA HSC PIC', priority: 'Medium', enabled: 'Yes' },
    { event: 'Yokoten Shared', recipientRole: 'All Relevant Users', priority: 'Low', enabled: '' },
    { event: 'Improvement Action Closed', recipientRole: 'Auditor', priority: 'Medium', enabled: '' },
    { event: 'Verification Completed', recipientRole: 'PIC', priority: 'Medium', enabled: '' },
    { event: 'Yokoten Published', recipientRole: 'All Concerned Users', priority: 'Low', enabled: '' },
  ],
  systemSettings: [
    { settingName: 'Application Name', value: 'Drive Pulse - DISHA HSC', description: 'System name displayed across application' },
    { settingName: 'Application Version', value: '1', description: 'Current application version' },
    { settingName: 'Mobile Login Enabled', value: 'Yes', description: 'Allow login using registered mobile number' },
    { settingName: 'Password Reset Allowed', value: 'Yes', description: 'Users can reset password through admin' },
    { settingName: 'Mandatory Password Change on First Login', value: 'Yes', description: 'Force users to change default password' },
    { settingName: 'Multi Location Support', value: 'Yes', description: 'Support multiple locations' },
    { settingName: 'Multi Department Support', value: 'Yes', description: 'Support multiple departments' },
    { settingName: 'Audit Versioning Enabled', value: 'Yes', description: 'Maintain audit checklist versions' },
    { settingName: 'Checklist Approval Required', value: 'Yes', description: 'Checklist changes require approval' },
    { settingName: 'Auto Generate Improvement Action', value: 'Yes', description: 'Create improvement action automatically for NG findings' },
    { settingName: '5 Why Mandatory for Critical Findings', value: 'Yes', description: 'Root cause analysis required' },
    { settingName: 'Countermeasure Approval Required', value: 'Yes', description: 'Approval before implementation' },
    { settingName: 'Cost Approval Workflow Enabled', value: 'Yes', description: 'Route costs through approval matrix' },
    { settingName: 'Verification Mandatory', value: 'Yes', description: 'Auditor verification required before closure' },
    { settingName: 'Yokoten Enabled', value: 'Yes', description: 'Improvement sharing functionality enabled' },
    { settingName: 'AI Sensei Enabled', value: 'Yes', description: 'Enable AI assistance' },
    { settingName: 'AI Root Cause Suggestion', value: 'Yes', description: 'AI can suggest root causes' },
    { settingName: 'AI Countermeasure Suggestion', value: 'Yes', description: 'AI can suggest countermeasures' },
    { settingName: 'AI Yokoten Suggestion', value: 'Yes', description: 'AI can suggest Yokoten opportunities' },
    { settingName: 'AI Executive Summary Enabled', value: 'Yes', description: 'AI can generate management summaries' },
    { settingName: 'AI Auto Approval Allowed', value: 'No', description: 'AI cannot approve actions' },
    { settingName: 'Evidence Upload Mandatory', value: 'Yes', description: 'Evidence required where applicable' },
    { settingName: 'Evidence Retention Period', value: '5 Years', description: 'Default evidence retention' },
    { settingName: 'Audit Report Auto Generation', value: 'Yes', description: 'Generate PDF audit reports' },
    { settingName: 'Notification Center Enabled', value: 'Yes', description: 'In-app notifications enabled' },
    { settingName: 'Email Notifications Enabled', value: 'Future', description: 'Reserved for future implementation' },
    { settingName: 'WhatsApp Notifications Enabled', value: 'Future', description: 'Reserved for future implementation' },
    { settingName: 'Escalation Engine Enabled', value: 'Yes', description: 'Automatic escalation of overdue actions' },
    { settingName: 'Audit Calendar Enabled', value: 'Yes', description: 'Audit planning calendar enabled' },
    { settingName: 'Management Review Enabled', value: 'Yes', description: 'Monthly review module enabled' },
    { settingName: 'Dashboard Refresh Frequency', value: 'Real Time', description: 'Refresh dashboard data instantly' },
    { settingName: 'Audit Trail Enabled', value: 'Yes', description: 'Track all user activities' },
    { settingName: 'Soft Delete Enabled', value: 'Yes', description: 'Archive records instead of permanent deletion' },
    { settingName: 'Data Export Enabled', value: 'Yes', description: 'Allow Excel/PDF exports' },
    { settingName: 'Backup Frequency', value: 'Daily', description: 'Database backup frequency' },
    { settingName: 'User Session Timeout', value: '30 Minutes', description: 'Auto logout after inactivity' },
    { settingName: 'Maximum Attachment Size', value: '10 MB', description: 'Maximum upload file size' },
    { settingName: 'Supported File Types', value: 'JPG, PNG, PDF, XLSX, DOCX', description: 'Allowed upload formats' },
    { settingName: 'System Administrator Role Enabled', value: 'Yes', description: 'Enable full system administration role' },
    { settingName: 'Maintenance Mode', value: 'No', description: 'Disable system access during maintenance' },
    { settingName: 'Active Status', value: 'Yes', description: 'Application active and available for use' },
    { settingName: 'Toyota HanSaChu Mode', value: 'Yes', description: 'Enable Toyota-specific audit workflow' },
    { settingName: 'Weighted Scoring Enabled', value: 'Yes', description: 'Use criticality-based scoring' },
    { settingName: 'Repeat Finding Detection', value: 'Yes', description: 'Auto-identify recurring findings' },
    { settingName: 'Guest Impact Scoring Enabled', value: 'Yes', description: 'Track customer impact of findings' },
    { settingName: 'Critical Finding Immediate Escalation', value: 'Yes', description: 'Instant escalation workflow' },
    { settingName: 'AI Learning Mode', value: 'No', description: 'AI suggestions do not learn from user data automatically' },
    { settingName: 'Audit Closure Lock', value: 'Yes', description: 'Closed audits cannot be edited' },
    { settingName: 'Evidence Deletion Allowed After Closure', value: 'No', description: 'Preserve audit integrity' },
    { settingName: 'Max Photos Per Finding', value: '20', description: '' },
    { settingName: 'Max Documents Per Finding', value: '5', description: '' },
    { settingName: 'GPS Capture Enabled', value: 'Yes', description: '' },
    { settingName: 'Offline Audit Mode', value: 'Future', description: '' },
    { settingName: 'Auto Save Interval', value: '30 Seconds', description: '' },
  ],
  auditTrail: [
    { action: 'Governance settings created', by: 'System Administrator', at: '16 Jun 2026 09:15', detail: 'Workbook master defaults loaded.' },
  ],
}
