import { createContext, useCallback, useContext, useMemo, useState } from 'react'

const CAPA_KEY = 'disha-hsc-capas'
const CapaContext = createContext(null)

const statusOptions = ['Open', 'Root Cause Analysis', 'Countermeasure Planned', 'Approval Pending', 'Implementation In Progress', 'Evidence Uploaded', 'Verification Pending', 'Closed', 'Yokoten Shared', 'Cancelled']

const legacyStatusMap = {
  'Action Planned': 'Countermeasure Planned',
  'Awaiting Approval': 'Approval Pending',
  'In Progress': 'Implementation In Progress',
  'Action in progress': 'Implementation In Progress',
  'Awaiting approval': 'Approval Pending',
  Verification: 'Verification Pending',
  Overdue: 'Open',
}

function normalizeStatus(status) {
  return legacyStatusMap[status] || status || 'Open'
}

function formatDate(date) {
  return new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }).format(date)
}

function formatDateTime(date) {
  return new Intl.DateTimeFormat('en-GB', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' }).format(date)
}

const emptyVerification = {
  implementationVerified: false,
  effectivenessRating: '',
  comments: '',
  evidenceReview: '',
}

const emptyAiSenseiHistoryEntry = {
  reviewStatus: 'Draft',
  reviewedBy: '',
  reviewDate: '',
  finalDecision: 'Pending',
  editedAfterSave: false,
  savedStatus: 'Saved',
  aiSuggestionUseful: '',
  aiUsefulnessRating: '',
  aiRatingReason: '',
  aiSuggestionImplemented: '',
  finalActionChangedByHuman: '',
}

function normalizeAiSenseiHistory(history) {
  return Array.isArray(history)
    ? history.map(entry => ({ ...emptyAiSenseiHistoryEntry, ...entry, reviewStatus: entry.reviewStatus || 'Draft', finalDecision: entry.finalDecision || 'Pending' }))
    : []
}

function dateKey(date) {
  return `${date.getFullYear()}${String(date.getMonth() + 1).padStart(2, '0')}${String(date.getDate()).padStart(2, '0')}`
}

function riskFromQuestion(question) {
  if (question.classification === 'Compliance' && question.guestImpact === 'High') return 'Critical'
  if (question.guestImpact === 'High') return 'Major'
  return 'Minor'
}

function targetDateForRisk(risk, createdAt) {
  const days = risk === 'Critical' ? 2 : risk === 'Major' ? 7 : 14
  const target = new Date(createdAt)
  target.setDate(target.getDate() + days)
  return target
}

function normalizeSeed(record) {
  return {
    ...record,
    capaId: record.id,
    auditId: record.audit,
    dishaQuestionNo: record.questionNo || 'Legacy finding',
    finding: record.issue,
    area: record.department,
    chapter: 'Legacy Improvement Action',
    classification: 'Process',
    locationAspect: 'Dealership',
    guestExperienceImpact: record.severity === 'Critical' ? 'High' : 'Medium',
    facilityType: '3S',
    departmentOwner: record.department,
    riskLevel: record.severity,
    auditorRemarks: record.issue,
    evidenceRequired: true,
    evidenceUploaded: record.progress >= 80,
    createdDate: '12 Jun 2026',
    targetDate: record.due,
    status: normalizeStatus(record.status),
    autoGenerated: false,
    repeatFinding: false,
    fiveWhys: ['', '', '', '', ''],
    rootCauseSummary: '',
    aiSenseiHistory: [],
    countermeasurePlan: {
      temporary: '', permanent: '', responsiblePerson: '', supportingDepartment: '', targetCompletionDate: '', estimatedCost: '', approvalRequired: 'No', approver: '', expectedResult: '', implementationStatus: 'Planned',
    },
    verification: emptyVerification,
    verificationHistory: [],
  }
}

function readCapas() {
  try {
    const stored = JSON.parse(localStorage.getItem(CAPA_KEY))
    return Array.isArray(stored) ? stored.map(record => ({ ...record, status: normalizeStatus(record.status), repeatFinding: Boolean(record.repeatFinding), fiveWhys: Array.isArray(record.fiveWhys) ? record.fiveWhys : ['', '', '', '', ''], rootCauseSummary: record.rootCauseSummary || '', aiSenseiHistory: normalizeAiSenseiHistory(record.aiSenseiHistory), countermeasurePlan: { temporary: '', permanent: '', responsiblePerson: '', supportingDepartment: '', targetCompletionDate: '', estimatedCost: '', approvalRequired: 'No', approver: '', expectedResult: '', implementationStatus: 'Planned', ...(record.countermeasurePlan || {}) }, verification: { ...emptyVerification, ...(record.verification || {}) }, verificationHistory: Array.isArray(record.verificationHistory) ? record.verificationHistory : [] })) : []
  } catch {
    return []
  }
}

export function CapaProvider({ children }) {
  const [capas, setCapas] = useState(readCapas)

  const commit = useCallback(updater => {
    setCapas(current => {
      const next = typeof updater === 'function' ? updater(current) : updater
      localStorage.setItem(CAPA_KEY, JSON.stringify(next))
      return next
    })
  }, [])

  const upsertAutoCapa = useCallback(({ auditId, auditLocation, auditDepartments, question, remarks, currentCondition, gapIdentified, evidenceUploaded }) => {
    commit(current => {
      const existingIndex = current.findIndex(item => item.auditId === auditId && item.dishaQuestionNo === question.id && item.autoGenerated)
      const now = new Date()
      const riskLevel = riskFromQuestion(question)
      const auditDepartmentLabel = Array.isArray(auditDepartments) ? auditDepartments.filter(Boolean).join(', ') : String(auditDepartments || '').trim()
      const shared = {
        auditId,
        audit: auditId,
        dishaQuestionNo: question.id,
        finding: question.question,
        issue: question.question,
        area: question.area,
        chapter: question.chapter,
        classification: question.classification,
        locationAspect: question.locationAspect,
        auditLocation: auditLocation || '',
        auditDepartments: Array.isArray(auditDepartments) ? auditDepartments.filter(Boolean) : [],
        guestExperienceImpact: question.guestImpact,
        facilityType: question.facilityType,
        departmentOwner: auditDepartmentLabel || question.departmentOwner || question.area,
        department: auditDepartmentLabel || question.departmentOwner || question.area,
        location: auditLocation || question.locationAspect || '',
        riskLevel,
        severity: riskLevel,
        currentCondition: currentCondition || '',
        gapIdentified: gapIdentified || '',
        auditorRemarks: remarks || currentCondition || '',
        evidenceRequired: question.evidenceRequired,
        evidenceUploaded: Boolean(evidenceUploaded),
        status: evidenceUploaded ? 'Evidence Uploaded' : 'Open',
        progress: evidenceUploaded ? 25 : 10,
        pic: 'Department PIC',
        cost: 'Assessment pending',
        autoGenerated: true,
      }

      if (existingIndex >= 0) {
        const existing = current[existingIndex]
        const updated = { ...existing, ...shared, status: existing.status === 'Cancelled' ? shared.status : existing.status }
        if (evidenceUploaded && ['Open', 'Root Cause Analysis', 'Evidence Uploaded'].includes(updated.status)) updated.status = 'Evidence Uploaded'
        const next = [...current]
        next[existingIndex] = updated
        return next
      }

      const prefix = `CAPA-${dateKey(now)}-`
      const sequence = current.filter(item => String(item.capaId || item.id).startsWith(prefix)).length + 1
      const capaId = `${prefix}${String(sequence).padStart(3, '0')}`
      const targetDate = targetDateForRisk(riskLevel, now)
      return [{
        ...shared,
        id: capaId,
        capaId,
        repeatFinding: false,
        fiveWhys: ['', '', '', '', ''],
        rootCauseSummary: '',
        aiSenseiHistory: [],
        countermeasurePlan: {
          temporary: '', permanent: '', responsiblePerson: '', supportingDepartment: '', targetCompletionDate: '', estimatedCost: '', approvalRequired: 'No', approver: '', expectedResult: '', implementationStatus: 'Planned',
        },
        verification: emptyVerification,
        verificationHistory: [],
        createdDate: formatDate(now),
        targetDate: formatDate(targetDate),
        due: formatDate(targetDate),
      }, ...current]
    })
  }, [commit])

  const cancelAutoCapa = useCallback((auditId, questionNo) => {
    commit(current => current.map(item => item.auditId === auditId && item.dishaQuestionNo === questionNo && item.autoGenerated ? { ...item, status: 'Cancelled', progress: 0 } : item))
  }, [commit])

  const deleteCapasByAudit = useCallback(auditId => {
    commit(current => current.filter(item => {
      const linkedAuditId = item.auditId || item.audit
      if (linkedAuditId !== auditId) return true
      return String(item.status || '').trim().toLowerCase() === 'closed'
    }))
  }, [commit])

  const updateCapaStatus = useCallback((capaId, status) => {
    commit(current => current.map(item => item.capaId === capaId ? { ...item, status } : item))
  }, [commit])

  const updateImprovementAnalysis = useCallback((capaId, updates) => {
    commit(current => current.map(item => item.capaId === capaId ? { ...item, ...updates } : item))
  }, [commit])

  const submitVerification = useCallback((capaId, verification) => {
    commit(current => current.map(item => {
      if (item.capaId !== capaId) return item

      const resultingStatus = verification.effectivenessRating === 'Not Effective'
        ? 'Countermeasure Planned'
        : verification.effectivenessRating === 'Effective'
          ? 'Closed'
          : 'Verification Pending'
      const historyEntry = {
        id: `VER-${Date.now()}`,
        ...verification,
        auditor: 'Mock Auditor',
        verifiedAt: formatDateTime(new Date()),
        resultingStatus,
      }

      return {
        ...item,
        verification,
        verificationNote: verification.comments,
        verificationHistory: [historyEntry, ...(item.verificationHistory || [])],
        status: resultingStatus,
        progress: resultingStatus === 'Closed' ? 100 : resultingStatus === 'Countermeasure Planned' ? 45 : 90,
      }
    }))
  }, [commit])

  const value = useMemo(() => ({ capas, statusOptions, upsertAutoCapa, cancelAutoCapa, deleteCapasByAudit, updateCapaStatus, updateImprovementAnalysis, submitVerification }), [capas, upsertAutoCapa, cancelAutoCapa, deleteCapasByAudit, updateCapaStatus, updateImprovementAnalysis, submitVerification])
  return <CapaContext.Provider value={value}>{children}</CapaContext.Provider>
}

export function useCapas() {
  const context = useContext(CapaContext)
  if (!context) throw new Error('useCapas must be used inside CapaProvider')
  return context
}

export function useOptionalCapas() {
  return useContext(CapaContext)
}
