import { AlertTriangle, CheckCircle2, Clock3, Search, Target } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { filterByUserAccess, useAuth } from '../auth/AuthContext'
import { PageHeader, Progress, StatCard, StatusBadge } from '../components/UI'
import { useCapas } from '../capa/CapaContext'

const filters = ['All', 'Open', 'Root Cause Analysis', 'Countermeasure Planned', 'Approval Pending', 'Implementation In Progress', 'Evidence Uploaded', 'Verification Pending', 'Closed', 'Yokoten Shared']

export default function CapaTracker() {
  const { capas } = useCapas()
  const { user } = useAuth()
  const [filter, setFilter] = useState('All')
  const [search, setSearch] = useState('')
  const navigate = useNavigate()
  const scopedCapas = filterByUserAccess(user, capas, capa => ({ department: capa.departmentOwner || capa.department || capa.area, location: capa.location || capa.locationAspect }))
  const activeCapas = scopedCapas.filter(capa => !['Cancelled', 'Closed', 'Yokoten Shared'].includes(capa.status))

  const rows = useMemo(() => {
    const query = search.trim().toLowerCase()
    return scopedCapas.filter(capa => filter === 'All' || capa.status === filter).filter(capa => !query || [capa.capaId, capa.finding, capa.auditId, capa.dishaQuestionNo, capa.departmentOwner, capa.status].some(value => String(value).toLowerCase().includes(query)))
  }, [scopedCapas, filter, search])

  return <>
    <PageHeader eyebrow="TOYOTA IMPROVEMENT MANAGEMENT" title="Improvement Tracker" description="Manage observations from gap identification through verification and Yokoten sharing." />
    <div className="stats-grid compact">
      <StatCard label="Open actions" value={String(activeCapas.length).padStart(2, '0')} meta="Active improvement actions" icon={Target} />
      <StatCard label="Auto-generated" value={String(scopedCapas.filter(capa => capa.autoGenerated).length).padStart(2, '0')} meta="Created from audit gaps" icon={Clock3} tone="amber" />
      <StatCard label="Verification pending" value={String(scopedCapas.filter(capa => capa.status === 'Verification Pending').length).padStart(2, '0')} meta="Ready for auditor" icon={CheckCircle2} tone="green" />
      <StatCard label="Critical findings" value={String(activeCapas.filter(capa => capa.riskLevel === 'Critical').length).padStart(2, '0')} meta="Immediate attention" icon={AlertTriangle} tone="dark" />
    </div>

    <div className="tabs">{filters.map(item => <button className={filter === item ? 'active' : ''} onClick={() => setFilter(item)} key={item}>{item} <span>{item === 'All' ? scopedCapas.length : scopedCapas.filter(capa => capa.status === item).length}</span></button>)}</div>
    <div className="search-bar capa-search"><Search size={18} /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search improvement ID, audit, question or department" /></div>

    <div className="card capa-table">
      <div className="capa-table-head auto-capa-head"><span>Finding</span><span>Audit reference</span><span>Department</span><span>Target date</span><span>Status</span></div>
      {rows.length ? rows.map(capa => <button className="capa-row auto-capa-row" key={capa.capaId} onClick={() => navigate(`/improvements/${capa.capaId}`)}>
        <div><div className="id-line"><strong>{capa.capaId}</strong><span className={`severity ${String(capa.riskLevel).toLowerCase()}`}>{capa.riskLevel}</span>{capa.autoGenerated && <span className="auto-badge">AUTO</span>}</div><b>{capa.finding}</b><small>{capa.area} · {capa.chapter}</small></div>
        <div><b>{capa.auditId}</b><small>{capa.dishaQuestionNo}</small></div>
        <div><b>{capa.departmentOwner}</b><small>{capa.locationAspect}</small></div>
        <div><b>{capa.targetDate}</b><small>Created {capa.createdDate}</small></div>
        <div><StatusBadge>{capa.status}</StatusBadge><Progress value={capa.progress || 0} /></div>
      </button>) : <div className="capa-empty"><Target /><strong>No improvement actions found</strong><span>Audit gaps will appear here automatically.</span></div>}
    </div>
  </>
}
